name: Coala
version: 1.0
main: com.coala.coalaplugin.Main

commands:
  clean:
    description: "플레이어 주변을 청소합니다."
  event:
    description: "이벤트 처리를 활성화/비활성화 합니다."
  move:
    description: "해당 월드로 이동합니다."
    aliases: ["이동"]
  start:
    description: "게임을 시작합니다."