name: Coalab
version: 1.02
main: com.mateatdang.coalab.Coalab

commands:
  compass:
    description: "동서납북 방향을 표시합니다."
  forward:
    description: "현재 바라보는 방향으로 전진합니다."
  start:
    description: "보물찾기 게임을 시작합니다."
  peace:
    description: "난이도를 평화로움으로 변경합니다."
  clean:
    description: "플레이어 주변을 청소합니다."