name: Coala
version: 1.03
main: com.coala.coalaplugin.Main

commands:
  clean:
    description: "플레이어 주변을 정리합니다."
    aliases: ["청소"]
#  event:
#    description: "이벤트 처리를 활성화/비활성화 합니다."
  move:
    description: "해당 월드로 이동합니다."
    aliases: ["이동"]
  start:
    description: "보물찾기1/보물찾기2 게임을 시작합니다."
    aliases: ["시작"]
  come:
    description: "플레이어들을 내 주변으로 소환합니다."
    aliases: ["소환"]
  create:
    description: "기본/평지/넓은 생물군계/지형이 높은 타입의 월드를 생성합니다."
    aliases: ["생성"]
  rabbit:
    description: "플레이어 주위에 토끼를 뿌립니다."
  freeze:
    description: "플레이어의 몸을 얼려 움직이지 못하게 만듭니다."
  mobfreeze:
    description: "몹들을 얼리거나 녹입니다."
  chatPaused:
    description: "플레이어들의 채팅을 제한/허용합니다."
  commandPaused:
    description: "플레이어들의 명령어 사용을 제한/허용합니다."
  playerInvincible:
    description: "플레이어가 모든 피해에 대하여 면역을 얻을지 설정합니다."
  preventExplode:
    description: "폭발에 의한 블록 변경을 막도록 설정합니다."
  preventPK:
    description: "플레이어와 플레이어 간의 피해를 입지 않도록 설정합니다."
  preventWorldEdit:
    description: "플레이어의 월드 변경을 제한/허용합니다."
#  modeAll:
#    description: "모든 플레이어의 게임 모드를 변경합니다."
#  giveAll:
#    description: "모든 플레이어에게 아이템을 제공합니다."
  classDefault:
    description: "기본 수업 환경으로 변경합니다."
  timer:
    description: "타이머를 설정합니다."
  unfreeze:
    description: "얼어붙은 플레이어를 움직일 수 있드록 합니다."
  weatherPlayer:
    description: "해당 플레이어가 있는 월드의 날씨를 변경합니다."